<a href="https://colab.research.google.com/github/aravindskumar98/DL/blob/main/PyTorch_Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## Tensors can be 1D 2D or 3D+

import torch

x = torch.empty(1)
print(x)

tensor([-3.5350e-09])


In [2]:
x = torch.empty(3) ##uninitialised tensor
print(x)

tensor([-3.5351e-09,  3.0780e-41,  3.3631e-44])


In [10]:
x = torch.zeros(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [11]:
x = torch.rand(1)
print(x)

tensor([0.3615])


In [13]:
x = torch.ones(2,3)
print(x.dtype)

torch.float32


In [14]:
x = torch.ones(2,3, dtype = torch.int)
print(x.dtype)

torch.int32


In [15]:
print(x.size())

torch.Size([2, 3])


In [17]:
##make from list
y = [2,3,4.5]

x = torch.tensor(y)
print(x)

tensor([2.0000, 3.0000, 4.5000])


In [18]:
## operations

x = torch.rand(2,2)
y = torch.rand(2,2)
z = x + y ## element wise additions
z1 = torch.add(x,y) ##same thing
print(x,y,z,z1)

tensor([[0.3891, 0.5238],
        [0.2636, 0.0364]]) tensor([[0.8139, 0.9528],
        [0.6845, 0.6395]]) tensor([[1.2030, 1.4765],
        [0.9480, 0.6758]]) tensor([[1.2030, 1.4765],
        [0.9480, 0.6758]])


In [19]:
## inplace additions
y.add_(x) ##modifies y
print(y)

tensor([[1.2030, 1.4765],
        [0.9480, 0.6758]])


In [20]:
## subtractions
t = torch.sub(x,y) ## t = x-y
m = torch.mul(x,y) ##x*y elementwise
d = torch.div(x,y) ## x/y -- elementwise


In [23]:
##slicing

x = torch.rand(5,3)
print(x)
print(x[:,0])
print(x[1,:])


tensor([[0.8963, 0.2661, 0.9312],
        [0.7264, 0.6143, 0.7322],
        [0.6077, 0.4772, 0.6704],
        [0.8181, 0.8597, 0.9911],
        [0.9012, 0.3844, 0.0384]])
tensor([0.8963, 0.7264, 0.6077, 0.8181, 0.9012])
tensor([0.7264, 0.6143, 0.7322])


In [24]:
print(x[1,1])

tensor(0.6143)


In [25]:
print(x[1,1].item()) ##gets actual value but can only be used if only one element present

0.6143475770950317


In [26]:
## reshape

x = torch.rand(4,4)
y = x.view(16)
print(x)
print(y)

tensor([[0.5507, 0.7887, 0.9404, 0.1277],
        [0.5863, 0.3021, 0.9792, 0.4845],
        [0.3963, 0.4878, 0.2281, 0.0096],
        [0.9297, 0.2670, 0.7781, 0.5593]])
tensor([0.5507, 0.7887, 0.9404, 0.1277, 0.5863, 0.3021, 0.9792, 0.4845, 0.3963,
        0.4878, 0.2281, 0.0096, 0.9297, 0.2670, 0.7781, 0.5593])


In [27]:
y = x.view(16,1)
print(y)


tensor([[0.5507],
        [0.7887],
        [0.9404],
        [0.1277],
        [0.5863],
        [0.3021],
        [0.9792],
        [0.4845],
        [0.3963],
        [0.4878],
        [0.2281],
        [0.0096],
        [0.9297],
        [0.2670],
        [0.7781],
        [0.5593]])


In [28]:
y = x.view(-1,8) ##pytorch understands -1 and fits size accordingly
print(y)


tensor([[0.5507, 0.7887, 0.9404, 0.1277, 0.5863, 0.3021, 0.9792, 0.4845],
        [0.3963, 0.4878, 0.2281, 0.0096, 0.9297, 0.2670, 0.7781, 0.5593]])


In [29]:
## numpy to torch and vise versa

import numpy as np

a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [31]:
b = a.numpy()
print(b,type(b)) ## CAUTION!!: if the tensor is on the CPU and not GPU then both objects will  share the same memory location

[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [32]:
a.add_(1)
print(a)

tensor([2., 2., 2., 2., 2.])


In [33]:
print(b) ## b is also modified since they point to the same memory location

[2. 2. 2. 2. 2.]


In [38]:

from torch._C import dtype
a = np.ones(5)
b = torch.from_numpy(a)
print(b,b.dtype) ## same location 

tensor([1., 1., 1., 1., 1.], dtype=torch.float64) torch.float64


In [39]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5, device=device)
  y = torch.ones(5) ##CPU
  y = y.to(device) ##moved to GPU
  z = x+y
  z.numpy() ##throws error as numpy can only act on CPU tensors

  z = z.to("cpu")
  z.numpy()

False

In [40]:
x = torch.ones(5, requires_grad = True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


# Revision Part 2 -- Gradient Calculation

In [74]:
### autograd package in pytorch

import torch 
x = torch.randn(3, requires_grad = True)
print(x)

tensor([0.5507, 1.5505, 0.0030], requires_grad=True)


In [75]:
y = x+2

In [76]:
print(y)
# y.backward()
print(x.grad)

tensor([2.5507, 3.5505, 2.0030], grad_fn=<AddBackward0>)
None


In [77]:
z = y*y*2
print(z)

tensor([13.0118, 25.2121,  8.0239], grad_fn=<MulBackward0>)


In [78]:
z = z.mean()
print(z)

tensor(15.4159, grad_fn=<MeanBackward0>)


In [79]:
c = z.backward() ## calculates dz/dx

In [80]:
print(x.grad) ## stores and prints gradient
print(c)

tensor([3.4009, 4.7340, 2.6706])
None


In [82]:
## for non scalar 
z = y*y*2
v = torch.tensor([0.1,0.1,0.001],dtype=torch.float32)
z.backward(v)
print(x.grad)

tensor([4.4212, 6.1542, 2.6787])


In [83]:
## prevent pytorch from tracking history // excluding a process from grad

#option 1 || x.requires_grad_(False)
#2 || y = x.detach() --- creates a new tensor without gradients
#3 || with torch.no_grad():

x.requires_grad_(False)

##or

with torch.no_grad():
  y = x+2
  print(y) ## no gradient


tensor([2.5507, 3.5505, 2.0030])


In [86]:
## whenever backward is called, this is acculmulated into x.grad

import torch
weights = torch.ones(4,requires_grad = True)
for epoch in range(3):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)

  weights.grad.zero_() ##resets to zero

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [ ]:
optimizer = torch.optim.SGD(weights,lr=0.01)
optimizer.step()
optimizer.zero_grad() ##same effect as above cell